name: dhakar_chaka
description: A Complete Free Route Finding Service For Dhaka Bashi. - Made With Love.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #searchable_dropdown: ^1.1.3
  shared_preferences: ^2.0.7
  search_choices: ^2.0.14
  cupertino_icons: ^1.0.2
  flutter_map: ^0.13.1 # or the latest version on Pub
  curved_navigation_bar: ^1.0.3
  rflutter_alert: ^2.0.4
  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.3.1
  flip_card: ^0.6.0
  url_launcher: ^6.0.20
  lottie: ^1.2.2
  animated_text_kit: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - lib/data/routeDetails.json
    - assets/
  uses-material-design: true
